[project]
name = "my-nft"
requirements = []
[contracts.create-nft]
path = "contracts/create-nft.clar"
depends_on = ["sip009-nft-trait"]

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
depends_on = []
